container:
# Utils:
  log:
    provider: Singleton
    provides: rag.modules.logs.logger.LoggerWrapper
    kwargs:
      logger_enabled:
        config: logger.enabled

  vector_evaluation_service:
    provider: Factory
    provides: rag.services.vector_evaluation_service.VectorEvaluationService

  url_service:
    provider: Factory
    provides: rag.services.url.UrlService

  text_cleaner_service:
    provider: Factory
    provides: rag.services.text_clean.TextCleanerService

  simple_text_splitter:
    provider: Factory
    provides: rag.modules.splitters.simple_text_splitter.SimplTextSplitters
    kwargs:
      chunk_size:
        config: retrievers.google_search.chunk_size

  recursive_text_splitter:
    provider: Factory
    provides: rag.modules.splitters.recursive_character_text_splitter.RecursiveCharacterTextSplitterWrapper
    kwargs_factory:
      512:
        chunk_size: 512
        chunk_overlap: 0
      512_64:
        chunk_size: 512
        chunk_overlap: 64
      1024:
        chunk_size: 1024
        chunk_overlap: 0
      1024_128:
        chunk_size: 1024
        chunk_overlap: 128
      2048:
        chunk_size: 2048
        chunk_overlap: 0
      2048_256:
        chunk_size: 2048
        chunk_overlap: 256

  json_file_loader:
    provider: Factory
    provides: rag.modules.file_loader.json.JsonFileLoader

# Drivers:
  embedding_driver:
    provider: Singleton
    provides: rag.drivers.embeddings.embedding.EmbeddingWrapper
    kwargs:
      model_name:
        config: embedding.clients.base.model_name
      driver:
        config: embedding.clients.base.driver

  google_search_driver:
    provider: Singleton
    provides: rag.drivers.google.google_search.GoogleSearch
    kwargs:
      app_key:
        config: google_search.clients.base.app_key
      app_secret:
        config: google_search.clients.base.app_secret
      api_url:
        config: google_search.clients.base.api_url

  download_page_driver:
    provider: Factory
    provides: rag.drivers.downloads.download_page.DownloadPage

  ollama_driver:
    provider: Singleton
    provides: rag.drivers.llms.ollama.OllamaClient
    kwargs_factory:
      config: ollama.models

  faiss_db_driver:
    provider: Singleton
    provides: rag.drivers.databases.faiss_db.FaissDB
    kwargs_factory:
      other_chunk:
        db_path: 'databases/other_chunk'
        embeddings:
          container: embedding_driver
      documents:
        db_path: 'databases/documents'
        embeddings:
          container: embedding_driver
      recursive_512:
        db_path: 'databases/recursive_512'
        embeddings:
          container: embedding_driver
      recursive_512_64:
        db_path: 'databases/recursive_512_64'
        embeddings:
          container: embedding_driver
      recursive_1024:
        db_path: 'databases/recursive_1024'
        embeddings:
          container: embedding_driver
      recursive_1024_128:
        db_path: 'databases/recursive_1024_128'
        embeddings:
          container: embedding_driver
      recursive_2048:
        db_path: 'databases/recursive_2048'
        embeddings:
          container: embedding_driver
      recursive_2048_256:
        db_path: 'databases/recursive_2048_256'
        embeddings:
          container: embedding_driver

# Other:
  chunk_utils:
    provider: Factory
    provides: rag.modules.document_evaluating.DocumentRelevanceEvaluator
    kwargs:
      embedding:
        container: embedding_driver
      vector_evaluation_service:
        container: vector_evaluation_service
      split_service:
        container: simple_text_splitter

# LLMs
  llm:
    provider: Factory
    provides: rag.modules.llms.ollama.OllamaLLM
    kwargs:
      client:
        container: ollama_driver__llama3_3

# Prompts:
  prompt:
    provider: Factory
    provides: rag.entities.prompt.Prompt
    kwargs:
      prompt:
        config: prompts.items.base.prompt

# Retrievers:
  faiss:
    provider: Singleton
    provides: rag.modules.retrievers.faiss.FAISSRetriever
    kwargs_factory:
      other_chunk:
        client:
          container: faiss_db_driver__other_chunk

  google_search_full:
    provider: Factory
    provides: rag.modules.retrievers.google_search.GoogleSearchFullRetriever
    kwargs:
      client:
        container: google_search_driver
      download_page:
        container: download_page_driver
      text_cleaner:
        container: text_cleaner_service
      url_service:
        container: url_service

  google_search_snippet:
    provider: Factory
    provides: rag.modules.retrievers.google_search.GoogleSearchSnippetRetriever
    kwargs:
      client:
        container: google_search_driver
      download_page:
        container: download_page_driver
      text_cleaner:
        container: text_cleaner_service
      url_service:
        container: url_service

  google_search_chunk:
    provider: Factory
    provides: rag.modules.retrievers.google_search.GoogleSearchChunkRetriever
    kwargs:
      client:
        container: google_search_driver
      download_page:
        container: download_page_driver
      text_cleaner:
        container: text_cleaner_service
      url_service:
        container: url_service
      document_evaluating:
        container: chunk_utils

# RAG:
  rag:
    provider: Factory
    provides: rag.modules.rag.simple_rag.SimpleRAG
    kwargs:
      retriever:
        container: faiss__other_chunk
      prompt:
        container: prompt
      llm:
        container: llm
      max_search_results: 3

# Indexer
  forward_indexer:
    provider: Factory
    provides: rag.modules.indexes.forward_indexer.ForwardIndexer
    kwargs_factory:
      other_chunk:
        db_client:
          container: faiss_db_driver__other_chunk
        file_loader:
          container: json_file_loader
      documents:
        db_client:
          container: faiss_db_driver__documents
        file_loader:
          container: json_file_loader

  splitter_indexer:
    provider: Factory
    provides: rag.modules.indexes.forward_indexer.ForwardIndexer
    kwargs_factory:
      512:
        splitter:
          container: recursive_text_splitter__512
        db_client:
          container: faiss_db_driver__512
        file_loader:
          container: json_file_loader
      512_64:
        splitter:
          container: recursive_text_splitter__512_64
        db_client:
          container: faiss_db_driver__512_64
        file_loader:
          container: json_file_loader
      1024:
        splitter:
          container: recursive_text_splitter__1024
        db_client:
          container: faiss_db_driver__1024
        file_loader:
          container: json_file_loader
      1024_128:
        splitter:
          container: recursive_text_splitter__1024_128
        db_client:
          container: faiss_db_driver__1024_128
        file_loader:
          container: json_file_loader
      2048:
        splitter:
          container: recursive_text_splitter__2048
        db_client:
          container: faiss_db_driver__2048
        file_loader:
          container: json_file_loader
      2048_256:
        splitter:
          container: recursive_text_splitter__2048_256
        db_client:
          container: faiss_db_driver__2048_256
        file_loader:
          container: json_file_loader