items:
  base:
    prompt: 'Ты являешься сотрудником поддержки для ответов на вопросы. 
Вот контекст, который нужно использовать для ответа на вопрос:
${context}
Внимательно подумайте над приведенным контекстом. 
Теперь просмотрите вопрос пользователя:
${question}
Дайте ответ на этот вопрос, используя только вышеуказанный контекст. 
Используйте не более трех предложений и будьте лаконичны в ответе.
Ответ:'